// Dữ liệu món ăn đầy đủ
const menuItems = [
  // COMBO ƯU ĐÃI
  {
    id: 1,
    name: "COMBO 4 (Mì Tương Đen + Trà Đào Cam Sả)",
    price: 69000,
    image: "https://i.ibb.co/JHvRgjK/pexels-fotios-photos-1279330.jpg",
    category: "COMBO ƯU ĐÃI",
    description: "Mì tương đen Hàn Quốc cay vừa, kèm trà đào cam sả tươi mát",
  },
  {
    id: 2,
    name: "COMBO 5 (Mì Bò/Hải Sản + Trà Ôlong)",
    price: 69000,
    image: "https://i.ibb.co/JvJ6Ykk/pexels-chan-walrus-941869.jpg",
    category: "COMBO ƯU ĐÃI",
    description:
      "Mì bò hoặc hải sản thơm ngon, kèm trà ôlong mật ong trân châu",
  },
  {
    id: 3,
    name: "COMBO 6 (Miến Trộn HQ + Trà Đào)",
    price: 69000,
    image: "https://i.ibb.co/BywVDgY/pexels-valeria-boltneva-1833337.jpg",
    category: "COMBO ƯU ĐÃI",
    description: "Miến trộn kiểu Hàn Quốc, kèm trà đào thơm mát",
  },
  {
    id: 4,
    name: "COMBO 7 (Mì Cay Hải Sản + Nước Ép Cam)",
    price: 75000,
    image: "https://i.ibb.co/fHnxPwz/pexels-jan-n-g-u-y-e-n-2591594.jpg",
    category: "COMBO ƯU ĐÃI",
    description: "Mì cay hải sản cấp độ 2, kèm nước ép cam tươi",
  },
  {
    id: 5,
    name: "COMBO 8 (Cơm Trộn + Trà Sữa Trân Châu)",
    price: 79000,
    image: "https://i.ibb.co/GCjZHWg/pexels-nadin-sh-3184183.jpg",
    category: "COMBO ƯU ĐÃI",
    description: "Cơm trộn Hàn Quốc truyền thống, kèm trà sữa trân châu",
  },
  {
    id: 6,
    name: "COMBO 9 (Tokbokki + Trà Táo)",
    price: 75000,
    image: "https://i.ibb.co/87GCJLZ/pexels-roman-odintsov-4551832.jpg",
    category: "COMBO ƯU ĐÃI",
    description: "Bánh gạo tokbokki cay ngọt, kèm trà táo xanh",
  },

  // MÌ CAY
  {
    id: 7,
    name: "Mì Cay Bò Cấp Độ 2",
    price: 55000,
    image: "https://i.ibb.co/Tv0KtQM/pexels-cottonbro-studio-3297801.jpg",
    category: "MÌ CAY",
    description: "Mì cay bò Hàn Quốc, độ cay vừa phải",
  },
  {
    id: 8,
    name: "Mì Cay Hải Sản Cấp Độ 3",
    price: 60000,
    image: "https://i.ibb.co/5YXJfmL/pexels-rajesh-tp-1624487.jpg",
    category: "MÌ CAY",
    description: "Mì cay hải sản tổng hợp, cay nồng đậm vị",
  },
  {
    id: 9,
    name: "Mì Cay Bò Mỹ Cấp Độ 4",
    price: 65000,
    image: "https://i.ibb.co/C2Mbh8j/pexels-engin-akyurt-1907244.jpg",
    category: "MÌ CAY",
    description: "Mì cay thịt bò Mỹ nhập khẩu, siêu cay",
  },
  {
    id: 10,
    name: "Mì Cay Tương Đen Cấp Độ 2",
    price: 55000,
    image: "https://i.ibb.co/SR3WrXQ/pexels-cats-coming-406152.jpg",
    category: "MÌ CAY",
    description: "Mì cay sốt tương đen đặc biệt, thơm ngon",
  },
  {
    id: 11,
    name: "Mì Cay Kimchi Thịt Heo",
    price: 60000,
    image: "https://i.ibb.co/JFRZMyx/pexels-ash-376464.jpg",
    category: "MÌ CAY",
    description: "Mì cay với kimchi và thịt heo xay",
  },
  {
    id: 12,
    name: "Mì Cay Chả Cá Cấp Độ 1",
    price: 55000,
    image: "https://i.ibb.co/GCjZHWg/pexels-nadin-sh-3184183.jpg",
    category: "MÌ CAY",
    description: "Mì cay với chả cá tươi, độ cay nhẹ cho người mới ăn",
  },
  {
    id: 13,
    name: "Mì Cay Hoa Quả Cấp Độ 5",
    price: 70000,
    image: "https://i.ibb.co/5YXJfmL/pexels-rajesh-tp-1624487.jpg",
    category: "MÌ CAY",
    description:
      "Mì siêu cay với các loại hoa quả nhiệt đới, thử thách cực đại",
  },
  {
    id: 14,
    name: "Mì Cay Trứng",
    price: 50000,
    image: "https://i.ibb.co/fHnxPwz/pexels-jan-n-g-u-y-e-n-2591594.jpg",
    category: "MÌ CAY",
    description: "Mì cay đơn giản với trứng luộc và rau xanh",
  },

  // MÌ XÀO KORE
  {
    id: 15,
    name: "Mì Xào Hải Sản Hàn Quốc",
    price: 65000,
    image: "https://i.ibb.co/5YXJfmL/pexels-rajesh-tp-1624487.jpg",
    category: "MÌ XÀO KORE",
    description: "Mì xào với hải sản tổng hợp, kiểu Hàn Quốc",
  },
  {
    id: 16,
    name: "Mì Xào Bò Bulgogi",
    price: 70000,
    image: "https://i.ibb.co/C2Mbh8j/pexels-engin-akyurt-1907244.jpg",
    category: "MÌ XÀO KORE",
    description: "Mì xào với thịt bò bulgogi truyền thống",
  },
  {
    id: 17,
    name: "Mì Xào Kimchi",
    price: 60000,
    image: "https://i.ibb.co/SR3WrXQ/pexels-cats-coming-406152.jpg",
    category: "MÌ XÀO KORE",
    description: "Mì xào với kimchi chua cay đặc trưng Hàn Quốc",
  },
  {
    id: 18,
    name: "Mì Đen Hàn Quốc",
    price: 65000,
    image: "https://i.ibb.co/JFRZMyx/pexels-ash-376464.jpg",
    category: "MÌ XÀO KORE",
    description: "Mì đen truyền thống Hàn Quốc với hành tây và rau xanh",
  },
  {
    id: 19,
    name: "Mì Xào Gà Teriyaki",
    price: 65000,
    image: "https://i.ibb.co/GCjZHWg/pexels-nadin-sh-3184183.jpg",
    category: "MÌ XÀO KORE",
    description: "Mì xào với thịt gà sốt teriyaki kiểu Hàn-Nhật fusion",
  },

  // CƠM VÀ MÓN KHÁC
  {
    id: 20,
    name: "Cơm Cá Ngừ + Súp RB + Trà Tắc",
    price: 75000,
    image: "https://i.ibb.co/QvHQJRP/pexels-kaboompics-com-5938.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Cơm với cá ngừ sốt đặc biệt, kèm súp và trà tắc",
  },
  {
    id: 21,
    name: "Cơm Trộn Hàn Quốc",
    price: 65000,
    image: "https://i.ibb.co/mhFNLKZ/pexels-adonyi-g-bor-1414234.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Cơm trộn với rau củ, trứng và thịt bò kiểu Hàn Quốc",
  },
  {
    id: 22,
    name: "Cơm Gà Teriyaki",
    price: 60000,
    image: "https://i.ibb.co/9bTMfwb/pexels-ella-olsson-1640772.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Cơm với thịt gà sốt teriyaki và rau củ",
  },
  {
    id: 23,
    name: "Miến Trộn Hàn Quốc",
    price: 60000,
    image: "https://i.ibb.co/X7SXH74/pexels-jane-doan-1099680.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Miến trộn lạnh kiểu Hàn Quốc với nước sốt mè rang",
  },
  {
    id: 24,
    name: "Cơm Cuộn Kimbap",
    price: 55000,
    image: "https://i.ibb.co/TRtBcJM/pexels-mariana-kurnyk-1775043.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Cơm cuộn với rau củ và thịt kiểu Hàn Quốc",
  },
  {
    id: 25,
    name: "Tokbokki",
    price: 60000,
    image: "https://i.ibb.co/87GCJLZ/pexels-roman-odintsov-4551832.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Bánh gạo cay ngọt kiểu Hàn Quốc",
  },
  {
    id: 26,
    name: "Cơm Chiên Kimchi",
    price: 60000,
    image: "https://i.ibb.co/QvHQJRP/pexels-kaboompics-com-5938.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Cơm chiên với kimchi và thịt ba chỉ",
  },
  {
    id: 27,
    name: "Súp Rong Biển",
    price: 30000,
    image: "https://i.ibb.co/mhFNLKZ/pexels-adonyi-g-bor-1414234.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Súp rong biển truyền thống Hàn Quốc",
  },
  {
    id: 28,
    name: "Canh Kim Chi",
    price: 40000,
    image: "https://i.ibb.co/9bTMfwb/pexels-ella-olsson-1640772.jpg",
    category: "CƠM VÀ MÓN KHÁC",
    description: "Canh kim chi cay nóng kiểu Hàn Quốc",
  },

  // COMBO
  {
    id: 29,
    name: "Combo Mì + Kimbap",
    price: 85000,
    image: "https://i.ibb.co/X7SXH74/pexels-jane-doan-1099680.jpg",
    category: "COMBO",
    description: "Combo mì cay cấp độ 2 với kimbap mini",
  },
  {
    id: 30,
    name: "Combo Tokbokki + Gà Rán",
    price: 95000,
    image: "https://i.ibb.co/TRtBcJM/pexels-mariana-kurnyk-1775043.jpg",
    category: "COMBO",
    description: "Combo tokbokki và gà rán kiểu Hàn",
  },
  {
    id: 31,
    name: "Combo Gia Đình",
    price: 199000,
    image: "https://i.ibb.co/yQmmMvd/pexels-lisa-fotios-1279330.jpg",
    category: "COMBO",
    description: "Combo đặc biệt cho 4 người với đa dạng món ăn",
  },

  // VIÊN CHIÊN ĂN VẶT
  {
    id: 32,
    name: "Há Cảo Chiên (6 viên)",
    price: 45000,
    image: "https://i.ibb.co/Wphz8LT/pexels-dana-tentis-725997.jpg",
    category: "VIÊN CHIÊN ĂN VẶT",
    description: "Há cảo nhân tôm chiên giòn",
  },
  {
    id: 33,
    name: "Viên Thịt Viên Chiên (8 viên)",
    price: 40000,
    image: "https://i.ibb.co/dgQ5KQy/pexels-pixabay-262959.jpg",
    category: "VIÊN CHIÊN ĂN VẶT",
    description: "Thịt viên chiên giòn kiểu Hàn Quốc",
  },
  {
    id: 34,
    name: "Khoai Tây Chiên",
    price: 35000,
    image: "https://i.ibb.co/w0f3wbB/pexels-dzenina-lukac-1583884.jpg",
    category: "VIÊN CHIÊN ĂN VẶT",
    description: "Khoai tây chiên giòn phủ phô mai",
  },
  {
    id: 35,
    name: "Gà Viên Chiên (6 viên)",
    price: 45000,
    image: "https://i.ibb.co/31M0QFy/pexels-ihsan-adityawarman-3521002.jpg",
    category: "VIÊN CHIÊN ĂN VẶT",
    description: "Gà viên chiên giòn với sốt cay ngọt",
  },
  {
    id: 36,
    name: "Phô Mai Viên (6 viên)",
    price: 40000,
    image: "https://i.ibb.co/PDtdxkM/pexels-daria-shevtsova-704971.jpg",
    category: "VIÊN CHIÊN ĂN VẶT",
    description: "Phô mai mozzarella chiên giòn ngoài mềm trong",
  },

  // NƯỚC
  {
    id: 37,
    name: "Trà Đào Cam Sả",
    price: 35000,
    image: "https://i.ibb.co/7vbYxJY/pexels-jl-photography-10812467.jpg",
    category: "NƯỚC",
    description: "Trà đào thơm ngon với cam và sả",
  },
  {
    id: 38,
    name: "Trà Ôlong Mật Ong",
    price: 35000,
    image: "https://i.ibb.co/8BkRZRX/pexels-nikolai-ulltang-2406715.jpg",
    category: "NƯỚC",
    description: "Trà ôlong với mật ong nguyên chất",
  },
  {
    id: 39,
    name: "Trà Sữa Trân Châu",
    price: 40000,
    image: "https://i.ibb.co/gtTWZvB/pexels-katerina-holmes-5908220.jpg",
    category: "NƯỚC",
    description: "Trà sữa truyền thống với trân châu đen",
  },
  {
    id: 40,
    name: "Nước Ép Cam",
    price: 35000,
    image: "https://i.ibb.co/SKVrKZ4/pexels-rov-camato-699544.jpg",
    category: "NƯỚC",
    description: "Nước ép cam tươi 100%",
  },
  {
    id: 41,
    name: "Sinh Tố Xoài",
    price: 40000,
    image: "https://i.ibb.co/b570NSg/pexels-alleksana-6107541.jpg",
    category: "NƯỚC",
    description: "Sinh tố xoài đặc creamy với topping trái cây",
  },
  {
    id: 42,
    name: "Soda Chanh",
    price: 30000,
    image: "https://i.ibb.co/QYKrq5h/pexels-valeria-boltneva-1695052.jpg",
    category: "NƯỚC",
    description: "Soda chanh mát lạnh",
  },
  {
    id: 43,
    name: "Trà Táo Xanh",
    price: 35000,
    image: "https://i.ibb.co/RPP37h7/pexels-tijana-drndarski-3338681.jpg",
    category: "NƯỚC",
    description: "Trà táo xanh thanh mát",
  },
  {
    id: 44,
    name: "Trà Tắc",
    price: 25000,
    image: "https://i.ibb.co/j9DY9QS/pexels-marta-dzedyshko-2097090.jpg",
    category: "NƯỚC",
    description: "Trà tắc truyền thống",
  },
  {
    id: 45,
    name: "Coca Cola",
    price: 20000,
    image: "https://i.ibb.co/SmMRkzv/pexels-pixabay-50593.jpg",
    category: "NƯỚC",
    description: "Coca Cola lon lạnh",
  },
  {
    id: 46,
    name: "Pepsi",
    price: 20000,
    image: "https://i.ibb.co/nQT3nqv/pexels-arnie-watkins-3915857.jpg",
    category: "NƯỚC",
    description: "Pepsi lon lạnh",
  },
  {
    id: 47,
    name: "7Up",
    price: 20000,
    image: "https://i.ibb.co/SmMRkzv/pexels-pixabay-50593.jpg",
    category: "NƯỚC",
    description: "7Up lon lạnh",
  },
  {
    id: 48,
    name: "Nước Suối",
    price: 15000,
    image: "https://i.ibb.co/GvwPm85/pexels-kampus-production-7312535.jpg",
    category: "NƯỚC",
    description: "Nước suối tinh khiết",
  },
  {
    id: 49,
    name: "Bia Heineken",
    price: 30000,
    image: "https://i.ibb.co/5R8XcBW/pexels-elevate-1267323.jpg",
    category: "NƯỚC",
    description: "Bia Heineken lon lạnh",
  },

  // MÓN THÊM
  {
    id: 50,
    name: "Kim Chi Cải Thảo",
    price: 25000,
    image: "https://i.ibb.co/NLx0CZQ/pexels-rene-asmussen-2544830.jpg",
    category: "MÓN THÊM",
    description: "Kim chi cải thảo chua cay truyền thống",
  },
  {
    id: 51,
    name: "Kim Chi Dưa Chuột",
    price: 20000,
    image: "https://i.ibb.co/GQJsgBM/pexels-valeria-boltneva-1833333.jpg",
    category: "MÓN THÊM",
    description: "Kim chi dưa chuột giòn ngon",
  },
  {
    id: 52,
    name: "Đậu Phụ Sốt Cay",
    price: 35000,
    image: "https://i.ibb.co/NLJM8y1/pexels-ash-376464.jpg",
    category: "MÓN THÊM",
    description: "Đậu phụ sốt cay kiểu Hàn",
  },
  {
    id: 53,
    name: "Salad Rong Biển",
    price: 30000,
    image: "https://i.ibb.co/GvwPm85/pexels-kampus-production-7312535.jpg",
    category: "MÓN THÊM",
    description: "Salad rong biển trộn mè",
  },
  {
    id: 54,
    name: "Kimbap Mini",
    price: 40000,
    image: "https://i.ibb.co/NLJM8y1/pexels-ash-376464.jpg",
    category: "MÓN THÊM",
    description: "Cơm cuộn nhỏ kiểu Hàn Quốc",
  },
  {
    id: 55,
    name: "Chả Cá Viên Chiên",
    price: 40000,
    image: "https://i.ibb.co/SR3WrXQ/pexels-cats-coming-406152.jpg",
    category: "MÓN THÊM",
    description: "Chả cá viên chiên giòn",
  },
  {
    id: 56,
    name: "Gà Rán (3 miếng)",
    price: 55000,
    image: "https://i.ibb.co/5YXJfmL/pexels-rajesh-tp-1624487.jpg",
    category: "MÓN THÊM",
    description: "Gà rán giòn kiểu Hàn Quốc",
  },
  {
    id: 57,
    name: "Canh Rong Biển",
    price: 25000,
    image: "https://i.ibb.co/fHnxPwz/pexels-jan-n-g-u-y-e-n-2591594.jpg",
    category: "MÓN THÊM",
    description: "Canh rong biển truyền thống",
  },
  {
    id: 58,
    name: "Kim Chi Củ Cải",
    price: 20000,
    image: "https://i.ibb.co/C2Mbh8j/pexels-engin-akyurt-1907244.jpg",
    category: "MÓN THÊM",
    description: "Kim chi củ cải chua cay",
  },
  {
    id: 59,
    name: "Bánh Gạo Tokbokki",
    price: 35000,
    image: "https://i.ibb.co/JFRZMyx/pexels-ash-376464.jpg",
    category: "MÓN THÊM",
    description: "Bánh gạo tokbokki sốt cay ngọt",
  },
  {
    id: 60,
    name: "Cơm Trắng",
    price: 15000,
    image: "https://i.ibb.co/GCjZHWg/pexels-nadin-sh-3184183.jpg",
    category: "MÓN THÊM",
    description: "Cơm trắng hạt dài thơm ngon",
  },
  {
    id: 61,
    name: "Trứng Luộc (2 quả)",
    price: 10000,
    image: "https://i.ibb.co/JHvRgjK/pexels-fotios-photos-1279330.jpg",
    category: "MÓN THÊM",
    description: "Trứng luộc chín tới",
  },

  // TOPPING THÊM
  {
    id: 62,
    name: "Phô Mai Bào",
    price: 10000,
    image: "https://i.ibb.co/GCjZHWg/pexels-nadin-sh-3184183.jpg",
    category: "TOPPING THÊM",
    description: "Phô mai bào tự nhiên",
  },
  {
    id: 63,
    name: "Trứng Ốp La",
    price: 8000,
    image: "https://i.ibb.co/JFRZMyx/pexels-ash-376464.jpg",
    category: "TOPPING THÊM",
    description: "Trứng ốp la vàng ươm",
  },
  {
    id: 64,
    name: "Thêm Thịt Bò",
    price: 25000,
    image: "https://i.ibb.co/C2Mbh8j/pexels-engin-akyurt-1907244.jpg",
    category: "TOPPING THÊM",
    description: "Thịt bò xay thêm",
  },
  {
    id: 65,
    name: "Thêm Hải Sản",
    price: 20000,
    image: "https://i.ibb.co/fHnxPwz/pexels-jan-n-g-u-y-e-n-2591594.jpg",
    category: "TOPPING THÊM",
    description: "Hải sản tổng hợp thêm",
  },
];

export default menuItems;
